import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Schedule from "@/components/Schedule";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <div className="App">
          <header className="App-header bg-blue-500 text-white p-4">
            <h1 className="text-3xl font-bold">Welcome to My Courses App</h1>
          </header>
          <main className="p-6">
            <Schedule />
          </main>
        </div>
        {children}
      </body>
    </html>
  );
}
